perde/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('bayi_girisi', views.site_login, name='login'),
    path('bayi_basvurusu', views.register, name='register'),
    path('logout', views.site_logout, name='logout'),
    path('siparis_olustur', views.create_order, name='create_order'),
    path('get_districts', views.get_districts, name='get_districts'),
]

perde/perde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perde/app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    STATUS_TYPES = [
        (0, 'Sipariş Oluşturulmadı.'),
        (1, 'Onay Bekliyor'),
        (2, 'Onaylandı'),
        (3, 'Kargoya Verildi'),
        (4, 'Teslim Edildi.'),
        (5, 'Onaylanmadı.'),
    ]
    status = models.IntegerField(choices=STATUS_TYPES, default=0)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    price = models.CharField(default="0", max_length=10)
    name = models.CharField(max_length=50, default="İsim")
    surname = models.CharField(max_length=50, default="Soyisim")
    province = models.CharField(max_length=100, default="İl")
    district = models.CharField(max_length=100, default="İlçe")
    phone = models.CharField(max_length=15, default="5554443322")
    address = models.TextField(default="Adres")


class Product(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    image = models.FileField()
    description = models.TextField()

    def __str__(self):
        return self.description


class Province(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class District(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

perde/app/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import *


def index(request):
    template_name = "app/index.html"
    return render(request, template_name, {})


def register(request):
    template_name = "app/register.html"
    return render(request, template_name, {})


def site_login(request):
    template_name = "app/login.html"
    return render(request, template_name, {})


def site_logout(request):
    logout(request)
    return redirect("app:index")


def create_order(request):
    template_name = "app/create_order.html"
    if request.user.is_authenticated:
        context = {}
        orders = Order.objects.filter(user=request.user, status=0).order_by('-pk')
        provinces = Province.objects.all()
        context["provinces"] = provinces
        if len(orders):
            order = orders[0]
            products = Product.objects.filter(order=order)
            context["order"] = order
            context["products"] = products
        else:
            order = Order()
            order.user = request.user
            order.status = 0
            order.save()
        if request.method == "POST":
            type = request.POST.get("type")
            if type == "add_product":
                image = request.FILES["image"]
                description = request.POST.get("description")

                product = Product()
                product.order = order
                product.image = image
                product.description = description
                product.save()
            elif type == "delete_product":
                Product.objects.filter(id=request.POST.get("productid")).delete()
        return render(request, template_name, context)
    else:
        return redirect("app:index")


@csrf_exempt
def get_districts(request):
    template_name = "parts/districts.html"
    provinceid = request.POST.get("pid")
    print(provinceid)
    districts = District.objects.filter(province__id=provinceid)
    return render(request, template_name, {"districts": districts})

perde/app/templates/app/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="tr">
{% load static %}
<head>
    <title>Pendik Perde</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}" type="text/css">
    <link rel="icon" type="image/png" href="{% static 'app/images/favicon.png' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Black+Ops+One|Modak|Ubuntu&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline|Comfortaa|Ubuntu:400,700&display=swap"
          rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
{% include "parts/top_navigation.html" %}
{% include "parts/main_navigation.html" %}
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
</html>

perde/app/templates/app/create_order.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}
<div class="card mt-3">
    <div class="card-body">
        <h5 class="mb-3"><i class="fas fa-plus-circle"></i> Perde Ekle</h5>
        <form class="needs-validation" method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <input type="hidden" name="type" value="add_product">
            <div class="form-row">
                <div class="col-sm-2">
                    <img id="blah" class="img-thumbnail" src="{% static 'app/images/perde.jpg' %}"/>
                </div>
                <div class="col-sm-10">
                    <textarea name="description" class="h-100 w-100 p-3" required
                              placeholder="Lütfen ürünü detaylı şekilde açıklayınız"></textarea>
                    <div class="invalid-feedback">
                        Lütfen geçerli bir telefon girin!
                    </div>
                </div>
            </div>
            <div class="form-row mt-2">
                <input type="file" id="imgInp" name="image" required>
                <div class="invalid-feedback">
                    Lütfen bir dosya seçin!
                </div>
                <button type="submit" class="btn btn-primary ml-auto"><i class="fas fa-plus-circle"></i>
                    Sepete Ekle
                </button>
            </div>
        </form>
    </div>
</div>

{% if products %}
<div class="card mt-3">
    <h5 class="m-3"><i class="fas fa-shopping-basket"></i> Sepettekiler</h5>
    <ul class="list-group list-group-flush">
        {% for product in products %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-sm-2">
                    <img src="{{product.image.url}}" class="w-100">
                </div>
                <div class="col-sm-8">
                    <p>{{product}}</p>
                </div>
                <div class="col-sm-2 row">
                    <form class="needs-validation ml-auto" method="post" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="productid" value="{{product.id}}">
                        <input type="hidden" name="type" value="delete_product">
                        <button class="btn btn-light" type="submit"><i class="fas fa-trash-alt"></i> Sil</button>
                    </form>
                </div>
            </div>
        </li>
        {% endfor%}
    </ul>
</div>

<div class="card mt-3 mb-5">
    <div class="card-body">
        <h5><i class="fas fa-user-tie"></i> Müşteri Bilgileri</h5>
        <form id="send_form" class="needs-validation ml-auto m-3" method="post" novalidate
              data-district_url="{% url 'app:get_districts' %}">
            {% csrf_token %}
            <div class="form-row mb-3">
                <div class="col-md-4">
                    <label for="validationCustom01">Ad</label>
                    <input type="text" class="form-control" id="validationCustom01" name="name" placeholder="Ad"
                           required>
                    <div class="invalid-feedback">
                        Lütfen geçerli bir ad girin!
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="validationCustom02">Soyad</label>
                    <input type="text" class="form-control" id="validationCustom02" name="surname"
                           placeholder="Soyad" required>
                    <div class="invalid-feedback">
                        Lütfen geçerli bir soyad girin!
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="validationCustomUsername">Telefon</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroupPrepend"><i
                                        class="fas fa-phone"></i></span>
                        </div>
                        <input type="number" class="form-control" id="validationCustomUsername" name="phone"
                               placeholder="5554443322" min="5000000000" max="5999999999"
                               aria-describedby="inputGroupPrepend" required>
                        <div class="invalid-feedback">
                            Lütfen geçerli bir telefon girin!
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row mb-3">
                <div class="col-md-6">
                    <label for="province">İl Seçin</label>
                    <select class="custom-select d-block w-100" name="province" id="province" required>
                        <option value="">İl Seçin...</option>
                        {% for province in provinces %}
                        <option value="{{province.id}}">{{province.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="district">İlçe Seçin</label>
                    <select class="custom-select d-block w-100" name="district" id="district" required>
                        <option value="">İlçe Seçin...</option>
                        {% for district in districts %}
                        <option value="districtid">{{district.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row mb-3">
                <div class="col-md-12">
                    <label for="address">Adres</label>
                    <textarea type="text" class="form-control" id="address" name="address"
                              placeholder="Adres" required></textarea>
                    <div class="invalid-feedback">
                        Lütfen geçerli bir adres girin!
                    </div>
                </div>
            </div>
            <div class="form-row">
                <button type="submit" class="btn btn-success ml-auto">Siparişi Gönder</button>
            </div>
        </form>
    </div>
</div>
{% endif %}

<script>
function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();

    reader.onload = function(e) {
      $('#blah').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}

$("#imgInp").change(function() {
  readURL(this);
});


$(function() {
    $('#province').change(function() {
        provinceid = $('#province').val()
        if (provinceid != ""){
            $('#district').hide();
            let urlDistricts = $('#send_form').data('district_url');
            $.ajax({
                url: urlDistricts,
                type: 'POST',
                data: {pid : $('#province').val()},
                success: function(response) {
                    $('#district').empty(); // clear the current elements in select box
                    $('#district').html(response);

                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert(errorThrown);
                }
            });
        }
    });
});


</script>

{% endblock %}

perde/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}
<div class="row mt-3">
    <div class="col-sm-8">
        {% include "parts/carousel.html" %}
    </div>
    <div class="col-sm-4">
        <div class="alert alert-primary" role="alert">
            This is a primary alert—check it out!
        </div>
    </div>
</div>
{% endblock %}

perde/app/templates/app/login.html
{% extends 'app/base.html' %}
{% block body %}
<br>
<div class="row d-flex justify-content-center">
    <div class="col-sm-6 jumbotron bg-light">
        {% if message %}
        <div class="alert alert-warning" role="alert">
            {{message}}
        </div>
        {% endif %}
        <br>
        <h3>Giriş Yap</h3>
        <hr>
        <form class="needs-validation" role="form" method="post" novalidate>
            {% csrf_token %}
            <div class="form-row mb-3">
                <label for="validationCustomEmail">Eposta</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrependEmail"><i class="fas fa-at"></i></span>
                    </div>
                    <input type="email" class="form-control" id="validationCustomEmail" name="email"
                           placeholder="Eposta"
                           aria-describedby="inputGroupPrependEmail" required>
                    <div class="invalid-feedback">
                        Lütfen geçerli bir eposta adresi girin!
                    </div>
                </div>
            </div>
            <div class="form-row mb-3">
                <label for="password">Şifre</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="password"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" id="validationCustom04" name="password"
                           placeholder="Şifre"
                           minlength="6" required>
                    <div class="invalid-feedback">
                        Şifrenizi girin!
                    </div>
                </div>
            </div>
            <br>
            <div class="form-row mb-3">
                <button type="submit" class="btn btn-block btn-success">Giriş Yap</button>
            </div>
            <br>
            <div class="form-row mb-3">
                <a href="{% url 'app:register'%}"> Hesap Oluştur</a>
                <a class="ml-3" href="#">Şifremi Unuttum </a>
            </div>
        </form>
    </div>
</div>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
{% endblock %}

perde/app/templates/app/register.html
{% extends 'app/base.html' %}
{% block body %}
<br>
{% if message %}
<div class="alert alert-warning" role="alert">
    {{message}}
</div>
{% endif %}
<br>
<div class="container jumbotron">
    {% if user.is_authenticated %}
    <h3>Legaling'e Kaydol</h3>
    <small>Kaydınızı tamamlamak için mesleğinizi seçin.</small>
    <hr>
    <form class="needs-validation" method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="register_type" value="google">
        <div class="form-row">
            <div class="col-md-12 mb-3">
                <label for="profession">Meslek Seçin</label>
                <select class="custom-select d-block w-100" name="profession" id="profession" required="">
                    <option value="">Meslek Seçin...</option>
                    <option>Avukat</option>
                    <option>Tercüman</option>
                    <option>Akademisyen</option>
                    <option>Hakim/Savcı</option>
                    <option>Öğrenci</option>
                    <option>Diğer</option>
                </select>
                <div class="invalid-feedback">
                    Lütfen geçerli bir meslek seçin!
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="invalidCheckx" required>
                <label class="form-check-label" for="invalidCheckx">
                    Şart ve koşulları kabul ediyorum.
                </label>
                <div class="invalid-feedback">
                    Kayıt olmak için şart ve koşulları kabul etmelisin.
                </div>
            </div>
        </div>
        <button class="btn btn-success btn-block" type="submit">Kaydol</button>
    </form>
    {% else %}
    <h3>Legaling'e Kaydol</h3>
    <small>Sitemize kaydolmak için bilgileri doğru ve eksiksiz doldurun.</small>
    <hr>
    <form class="needs-validation" method="post" novalidate>
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationCustom01">Ad</label>
                <input type="text" class="form-control" id="validationCustom01" name="name" placeholder="Ad" required
                       oninvalid="this.setCustomValidity('Lütfen geçerli bir ad girin!')"
                       oninput="setCustomValidity('')">
                <div class="invalid-feedback">
                    Lütfen geçerli bir ad girin!
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <label for="validationCustom02">Soyad</label>
                <input type="text" class="form-control" id="validationCustom02" name="surname" placeholder="Soyad"
                       required
                       oninvalid="this.setCustomValidity('Lütfen geçerli bir soyad numarası girin!')"
                       oninput="setCustomValidity('')">
                <div class="invalid-feedback">
                    Lütfen geçerli bir soyad girin!
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <label for="validationCustomUsername">Telefon</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrepend"><i class="fas fa-phone"></i></span>
                    </div>
                    <input type="number" class="form-control" id="validationCustomUsername" name="username"
                           placeholder="5554443322" min="5000000000" max="5999999999"
                           aria-describedby="inputGroupPrepend" required
                           oninvalid="this.setCustomValidity('Lütfen geçerli bir telefon numarası girin!')"
                           oninput="setCustomValidity('')">
                    <div class="invalid-feedback">
                        Lütfen geçerli bir telefon girin!
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="state">Meslek Seçin</label>
                <select class="custom-select d-block w-100" name="profession" id="state" required="">
                    <option value="">Meslek Seçin...</option>
                    <option>Avukat</option>
                    <option>Tercüman</option>
                    <option>Akademisyen</option>
                    <option>Hakim/Savcı</option>
                    <option>Öğrenci</option>
                    <option>Diğer</option>
                </select>
                <div class="invalid-feedback">
                    Lütfen geçerli bir meslek seçin!
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="validationCustomEmail">Email</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrependEmail"><i class="fas fa-at"></i></span>
                    </div>
                    <input type="email" class="form-control" id="validationCustomEmail" name="email" placeholder="Email"
                           aria-describedby="inputGroupPrependEmail" required>
                    <div class="invalid-feedback">
                        Lütfen Geçerli Bir Email Girin!
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="validationCustom04">Şifre</label>
                <input type="password" class="form-control" id="validationCustom04" name="password" placeholder="Şifre"
                       minlength="6" required>
                <div class="invalid-feedback">
                    En az 6 karakterli bir şifre girin!
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="validationCustom05">Şifre Yeniden</label>
                <input type="password" class="form-control" id="validationCustom05" name="repassword"
                       placeholder="Şifre Yeniden" minlength="6" required>
                <div class="invalid-feedback">
                    En az 6 karakterli bir şifre girin!
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                <label class="form-check-label" for="invalidCheck">
                    Şart ve koşulları kabul ediyorum.
                </label>
                <div class="invalid-feedback">
                    Kayıt olmak için şart ve koşulları kabul etmelisin.
                </div>
            </div>
        </div>
        <button class="btn btn-success btn-block" type="submit">Kaydol</button>
    </form>
    {% endif %}

</div>
<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

</script>
{% endblock %}

perde/app/templates/parts/carousel.html
<div class="card">
    <div class="card-body">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" height="400px"
                         src="https://support.apple.com/library/content/dam/edam/applecare/images/tr_TR/macos/Catalina/macos-catalina-migration-assistant-hero.jpg"
                         alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" height="400px"
                         src="https://media.kingston.com/hyperx/product/hx-product-mouse-pulsefire-surge-1-sm.jpg"
                         alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" height="400px"
                         src="https://support.apple.com/library/content/dam/edam/applecare/images/tr_TR/macos/Catalina/macos-catalina-migration-assistant-hero.jpg"
                         alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <h1><i class="fas fa-chevron-circle-left" style="color: #0d4f75;"></i></h1>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <h1><i class="fas fa-chevron-circle-right" style="color: #0d4f75;"></i></h1>
            </a>
        </div>
    </div>
</div>

perde/app/templates/parts/districts.html
<label for="district">İlçe Seçin</label>
<select class="custom-select d-block w-100" name="district" id="district" required>
    <option value="">İlçe Seçin...</option>
    {% for district in districts %}
    <option>{{district.name}}</option>
    {% endfor %}
</select>

perde/app/templates/parts/main_navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'app:index' %}">
            <img src="{% static 'app/images/pendikperde.png' %}" alt="Logo" height="40px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:index' %}"><i class="fas fa-home"></i> Anasayfa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:index' %}"><i class="fas fa-users"></i> Hakkımızda</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:index' %}"><i class="fas fa-th-list"></i> Siparişlerim</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:index' %}"><i class="fas fa-lira-sign"></i> Hak Edişlerim</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:create_order' %}"><i class="fas fa-plus-circle"></i> Yeni Sipariş Oluştur</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:index' %}"><i class="fas fa-envelope"></i> Bize Ulaşın</a>
                </li>
            </ul>

        </div>
    </div>
</nav>

perde/app/templates/parts/top_navigation.html
<nav id="navbar-top" class="navbar navbar-expand-lg navbar-light"
     style="background-color: #f2f2f2; border-bottom: 1px solid #d2d2d2;">
    <div class="container">
        <small class="ml-auto">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app:index' %}">
                        <i class="fas fa-address-book"></i> Bize Yazın
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="users" data-toggle="dropdown"><i
                            class="fas fa-user"></i> {{ user.first_name }} {{ user.last_name }}</a>
                    <div class="dropdown-menu">
                        <small>
                        <a class="dropdown-item active" href="{% url 'app:logout' %}"><i
                                class="fas fa-sign-out-alt"></i>
                            Çıkış Yap</a></small>
                    </div>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="user" data-toggle="dropdown"><i
                            class="fas fa-user"></i> Üyelik</a>
                    <div class="dropdown-menu">
                        <small>
                            <a class="dropdown-item" href="{% url 'app:login' %}"><i
                                    class="fas fa-sign-in-alt"></i>
                                Giriş Yap</a></small>
                        <small><a class="dropdown-item" href="{% url 'app:register' %}"><i
                                class="fas fa-user-plus"></i>
                            Bayimiz Olun</a></small>
                    </div>
                </li>
                {% endif %}
            </ul>
        </small>
    </div>
</nav>